Add /sys/kernel/debug VolumeMount when eBPF is in use
draios/sysdig-cloud-scripts pull request #169
Opened 2021-08-10 17:17 UTC by jcpittman144

Agent eBPF code requires access to the /sys/kernel/debug filesystem.
For certain kernel versions, this filesystem is not accessible by default
from within docker containers, so add a VolumeMount in the daemonset.

2021-08-10 17:40 UTC, balinaveen commented on agent_deploy/kubernetes/sysdig-agent-daemonset-v2.yaml
> +        #- mountPath: /root/.sysdig
Same comment applies to other daemonset files.

2021-08-10 17:40 UTC, balinaveen commented on agent_deploy/kubernetes/sysdig-agent-daemonset-v2.yaml
> +        #- mountPath: /sys/kernel/debug
Same comment applies to other daemonset files

2021-08-11 21:05 UTC, jcpittman144 commented on agent_deploy/kubernetes/sysdig-agent-daemonset-v2.yaml
> +        #- mountPath: /root/.sysdig
I agree, since /root is already available, no need for the subordinate directory /root/.sysdig

2021-08-11 21:06 UTC, jcpittman144 commented on agent_deploy/kubernetes/sysdig-agent-daemonset-v2.yaml
> +        #- mountPath: /sys/kernel/debug
Yes, I will change /sys/kernel/debug to readOnly throughout the daemonset files.

2021-08-12 07:07 UTC, deepskyblue86 requested changes

2021-08-12 07:07 UTC, deepskyblue86 commented on agent_deploy/kubernetes/sysdig-agent-slim-daemonset-v2.yaml
> +      #    path: /sys/kernel/debug
shouldn't this be:
```suggestion
      #- name: sys-tracing
      #  hostPath:
      #    path: /sys/kernel/debug
```
?

2021-08-12 07:07 UTC, deepskyblue86 commented on agent_deploy/kubernetes/sysdig-kmod-thin-agent-slim-daemonset.yaml
> +      #    path: /sys/kernel/debug
Same as my other comment: isn't `hostPath` missing?

2021-08-12 14:39 UTC, jcpittman144 commented on agent_deploy/kubernetes/sysdig-kmod-thin-agent-slim-daemonset.yaml
> +      #    path: /sys/kernel/debug
Yes, fix coming soon.  Thanks!

2021-08-12 19:45 UTC, nathan-b approved these changes
LGTM

2021-08-17 15:36 UTC, deepskyblue86 approved these changes

2021-08-18 08:57 UTC, papajulio approved these changes

2021-08-18 13:24 UTC, nathan-b commented on agent_deploy/kubernetes/sysdig-agent-daemonset-v2.yaml
> +#         path: /root
I'm not sure what the point of this change is...I'm not opposed to it, but if we want to go this route with the formatting we should be consistent throughout the file (lines 70-74, for instance, should follow the same pattern of column 1 comment marker and three comment markers at the start of the block comment). Either is fine, just make it consistent.

2021-08-18 15:56 UTC, nathan-b commented on agent_deploy/kubernetes/sysdig-agent-daemonset-v2.yaml
> +#         path: /root
Add jank to work around our other jank. Got it ;)

Fortunately, this jank is extremely low-magnitude. Thanks for the explanation!

2021-08-18 15:57 UTC, nathan-b approved these changes

2021-08-18 16:12 UTC, merged