[TSOPS-1382] Add streamsnap and storage settings to support bundle sc…
draios/sysdig-cloud-scripts pull request #220
Opened 2023-02-08 18:58 UTC by patrickhargett

…ript

Updating the support bundle script to gather storage and streamSnap settings, given that the user supplies the administrative API key. https://sysdig.atlassian.net/browse/TSOPS-1382

2023-02-09 15:37 UTC, dthomson-sysdig requested changes
We have an `agents/connected` a few lines down.

Not sure what the `checkStatus` REQUEST parameter does.

cc: @patrickhargett

2023-02-09 15:51 UTC, dthomson-sysdig approved these changes

2023-02-28 13:52 UTC, dthomson-sysdig approved these changes

2023-02-28 14:01 UTC, gmarraff approved these changes
LGTM!

2023-02-28 14:03 UTC, gmarraff reviewed
The streamsnap ino are in the second call?

2023-06-26 17:46 UTC, dthomson-sysdig approved these changes

2023-06-26 17:47 UTC, mbreitung approved these changes

2023-06-26 17:48 UTC, merged